### ISSUE TITLE
Can't run tests: test-utils missing

### ISSUE THREAD

**Issue by henry4k** [hoelzro/lua-repl#44]
Uhm .. Lua can't find it and I can neither find it in luarocks nor in your github repositories.
Any ideas where I could obtain it?

**Comment by hoelzro** [comment]
@henry4k How are you trying to run the tests? test-utils.lua is under `t/lib`, and `make test` should set up the environment to find it.

**Comment by henry4k** [comment]
Oh sorry, I didn't know that the tests are run using make.  I should've probably taken a look there first.
