### ISSUE TITLE
Suppress readline when TERM=dumb

### ISSUE THREAD

**Issue by technomancy** [hoelzro/lua-repl#47]
I'm trying to use lua-repl as a subprocess from within Emacs, but it crashes:

```
rlwrap: Oops, crashed (caught SIGFPE) - this should not have happened!
If you need a core dump, re-configure with --enable-debug and rebuild
Resetting terminal and cleaning up...

Process lua-repl finished
```

Emacs handles all the niceties of rlwrap, so using it is redundant. Using rlwrap is unlikely to work when TERM=dumb, so we should check for that before attempting to use it.

**Comment by technomancy** [comment]
Currently working around it by setting `LUA_REPL_RLWRAP` which fakes it out, but it'd be nice if it worked out of the box.

**Comment by hoelzro** [comment]
@technomancy I'm glad you have a workaround; another would be to copy the `rep.lua` file, remove the `rlwrap` logic, and have emacs invoke that.  I'd rather not add custom logic to detect TERM=dumb, though. I'll think about other possible solutions.

**Comment by hoelzro** [comment]
@technomancy I've changed the plugin loading logic so an rcfile only loads what plugins it asks for.
