### ISSUE TITLE
Continuous integration on Travis

### ISSUE THREAD

**Issue by iqbalansari** [hoelzro/lua-repl#54]
Hi,

Would be interested in adding Travis integration for this project? I have implemented it on a [branch](https://github.com/iqbalansari/lua-repl/tree/travis) and would open a pull request if you are interested

Thanks

**Comment by hoelzro** [comment]
Hi, I'm really sorry that I dropped the ball on this PR.  I just took a look, and everything looks great, so I integrated your change and pushed it up.  Thanks for adding Travis support?
